# Build and deploy to the test environment after creating a tag with the given pattern.

resources:
  repositories:
    # Azure DevOps repository.
    - repository: tilavarauspalvelu-pipelines
      type: git
      # Azure DevOps project/repository.
      name: tilavarauspalvelu/tilavarauspalvelu-pipelines

trigger:
  # If another instance of this pipeline is running,
  # wait for it to complete and then run all other changes in a batch.
  batch: true
  tags:
    # Trigger when creating tags like v1.0.0, v1.0.0-ui, v1.0.0-staff,
    # but not when creating tags like v1.0.0-customer, v1.0.0-core, etc.
    include:
      - "v*"
    exclude:
      - "*-customer"
      - "*-core"
  paths:
    include:
      - frontend/apps/staff
      - frontend/packages
    exclude:
      - README.md

# Don't use Azure pipelines for PRs.
pr: none

# By default, use self-hosted agents.
pool: Default

extends:
  # Filename for pipeline to extend from the Azure DevOps Repository.
  template: staff-ui-build-release.yml@tilavarauspalvelu-pipelines
