# Build and deploy to the development environment after merging to the main branch.

resources:
  repositories:
    # Azure DevOps repository.
    - repository: tilavarauspalvelu-pipelines
      type: git
      # Azure DevOps project/repository.
      name: tilavarauspalvelu/tilavarauspalvelu-pipelines

trigger:
  # If another instance of this pipeline is running,
  # wait for it to complete and then run all other changes in a batch.
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - frontend/apps/staff
      - frontend/packages
    exclude:
      - README.md

# Don't use Azure pipelines for PRs.
pr: none

# By default, use self-hosted agents.
pool: Default

extends:
  # Filename for pipeline to extend from the Azure DevOps Repository.
  template: staff-ui-build-dev.yml@tilavarauspalvelu-pipelines
