# This workflow will do a clean install of node dependencies, build the source code and run tests against node 14
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js lts/fermium (14)
      uses: actions/setup-node@v2-beta
      with:
        node-version: '14'
    - name: Run CI checks
      run: |
        yarn install --frozen-lockfile
        yarn lint
        yarn lint:css
        yarn build
        yarn test
    - name: Build image
      run: |
        docker build -t tilavaraus-ui .
    - name: Run server tests
      run: |
        docker run -p 3000:3000 -d --name tilavaraus-ui-server tilavaraus-ui
        yarn test:server
        docker stop tilavaraus-ui-server
