name: ui-e2e

on:
  push:
    branches: [main]
    paths:
      - "ui/**"
      - ".github/workflows/ui-e2e.yml"
      - "yarn.lock"
  pull_request:
    branches: [main]
    paths:
      - "ui/**"
      - ".github/workflows/ui-e2e.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CYPRESS_BASE_URL: http://localhost:3000
    environment:
      name: actions
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: |
          docker build -t tilavaraus-ui -f ui/Dockerfile .
      - name: Start container
        run: |
          docker run -e TZ=Europe/Helsinki -e DISABLE_AUTH=true -e TILAVARAUS_API_URL=http://localhost:8000 -e NEXT_PUBLIC_MOCK_REQUESTS=true -p 3000:3000 -d --ipc=host --name tilavaraus-ui-server tilavaraus-ui
      - name: Cypress e2e & a11y
        uses: cypress-io/github-action@v2
        with:
          project: ./ui
      - name: Upload images on failure
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: ui/cypress/screenshots
      - name: Upload videos
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: ui/cypress/videos
      - name: Stop container
        run: |
          docker stop tilavaraus-ui-server
