name: "Update commits to sentry release"

# release only (we upload to production sentry)
on:
  push:
    tags:
      - "v*"
  # NOTE workflow dispatch requires creating a sentry release with the same name
  # this workflow can only append the git commits to an existing release
  # also PRs and branch workflow_call have different ref_names
  workflow_dispatch:

# Cancel a workflow from the same PR, branch or tag when a new workflow is triggered.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  SKIP_ENV_VALIDATION: "true"
  SENTRY_ORG: "city-of-helsinki"
  SENTRY_URL: "https://sentry.hel.fi/"

jobs:
  upload-customer-sentry-sourcemaps:
    name: "Upload customer ui sentry sourcemaps"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: "Create release name"
        id: release
        run: >-
          echo "release=tilavarauspalvelu-ui@$(
            echo ${{ github.ref_name || github.sha }} | tr '/' '-'
          )" >> $GITHUB_OUTPUT
      - name: Print release
        run: echo ${{ steps.release.outputs.release }}
      - name: Create Sentry release
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_PROJECT: "tilavarauspalvelu-ui"
        with:
          environment: "prod"
          ignore_missing: true
          release: ${{ steps.release.outputs.release }}

  upload-admin-sentry-sourcemaps:
    name: "Upload admin ui sentry sourcemaps"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
        # release name can't contain slashes e.g. merge/PR_number
      - name: "Create release name"
        id: release
        run: >-
          echo "release=tilavarauspalvelu-admin-ui@$(
            echo ${{ github.ref_name || github.sha }} | tr '/' '-'
          )" >> $GITHUB_OUTPUT
      - name: Print release
        run: echo ${{ steps.release.outputs.release }}
      - name: Create Sentry release
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_PROJECT: "tilavarauspalvelu-admin-ui"
        with:
          environment: "prod"
          ignore_missing: true
          release: ${{ steps.release.outputs.release }}
